apiVersion: v1
kind: Pod
metadata:
  name: with-toleration-pod
spec:
  tolerations:
  - key: "workload"
    operator: "Equal"
    value: "worker"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx
