- name: install Nginx
  hosts: node
  become: yes
  tasks:

    - name: install and ensure Nginx is installed
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: create index.html
      copy: 
        dest: /var/www/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head><title>Hello</title></head>
          <body>
          <h1>Hello, world!</h1>
          </body> 
          </html>
