apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-logs-pv
spec:
  claimRef:
    namespace: ivolve
    name: app-logs-pvc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/app-logs

